Repository Granulate/granulate-utils, pull requests merged in 2022-09, with the labels that each got.

#56 cgroup support for memory and cpu limiting
  granulate_utils/linux/cgroups.py
  granulate_utils/linux/cgroups/__init__.py
  granulate_utils/linux/cgroups/base_cgroup.py
  granulate_utils/linux/cgroups/cpu_cgroup.py
  granulate_utils/linux/cgroups/memory_cgroup.py
Labels: granulate-utils

#71 fix circular import of ns
  granulate_utils/containers/cri.py
  granulate_utils/containers/docker.py
  granulate_utils/linux/cgroups/cgroup.py
  granulate_utils/linux/proc_events.py
Labels: bug

#75 cgroups: memory: fixed set_limit_in_bytes
  granulate_utils/linux/cgroups/memory_cgroup.py
Labels: bug

#77 Added get_elf_arch() that reads the binary architecture from the ELF section of the file
  granulate_utils/linux/elf.py
Labels: granulate-utils

#81 Add custom UnsupportedCGroupV2 error when initializing BaseCgroup
  .flake8
  granulate_utils/exceptions.py
  granulate_utils/linux/cgroups/base_cgroup.py
  granulate_utils/linux/cgroups/cgroup.py
  granulate_utils/linux/process.py
  lint.sh
Labels: enhancement
